Syndicata/Controllers/AppartementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Syndicata.Data;
using Syndicata.Models;

namespace Syndicata.Controllers
{
    public class AppartementsController : Controller
    {
        private SyndicataContext db = new SyndicataContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string actionName = filterContext.ActionDescriptor.ActionName;
            string controllerName = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName;
            Person user = Session["userInfo"] as Person;
            if (user == null || !Helper.CheckAutorization(actionName, controllerName, user.RoleId))
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Home"},
                        {"action", "NoAccess"}
                    });
                return;
            }
        }

        // GET: Appartements
        public ActionResult Index()
        {
            var appartements = db.Appartements.Include(a => a.Propritaire).Include(a => a.Residence);
            return View(appartements.ToList());
        }

        // GET: Appartements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartement appartement = db.Appartements.Include(_ => _.Propritaire).Include(_ => _.Residence).SingleOrDefault(_ => _.Id == id);
            if (appartement == null)
            {
                return HttpNotFound();
            }
            return View(appartement);
        }

        // GET: Appartements/Create
        public ActionResult Create()
        {
            ViewBag.PropritaireId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.ResidenceId = new SelectList(db.Coproprietes, "Id", "Nom");
            return View();
        }

        // POST: Appartements/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NumeroAppartement,Surface,Etage,ResidenceId,PropritaireId")] Appartement appartement)
        {
            if (ModelState.IsValid)
            {
                db.Appartements.Add(appartement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PropritaireId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.ResidenceId = new SelectList(db.Coproprietes, "Id", "Nom", appartement.ResidenceId);
            return View(appartement);
        }

        // GET: Appartements/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartement appartement = db.Appartements.Find(id);
            if (appartement == null)
            {
                return HttpNotFound();
            }
            ViewBag.PropritaireId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.ResidenceId = new SelectList(db.Coproprietes, "Id", "Nom", appartement.ResidenceId);
            return View(appartement);
        }

        // POST: Appartements/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NumeroAppartement,Surface,Etage,ResidenceId,PropritaireId")] Appartement appartement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appartement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PropritaireId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.ResidenceId = new SelectList(db.Coproprietes, "Id", "Nom", appartement.ResidenceId);
            return View(appartement);
        }

        // GET: Appartements/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appartement appartement = db.Appartements.Find(id);
            if (appartement == null)
            {
                return HttpNotFound();
            }
            return View(appartement);
        }

        // POST: Appartements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Appartement appartement = db.Appartements.Find(id);
            db.Appartements.Remove(appartement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Syndicata/Controllers/CommandesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Syndicata.Data;
using Syndicata.Models;

namespace Syndicata.Controllers
{
    public class CommandesController : Controller
    {
        private SyndicataContext db = new SyndicataContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string actionName = filterContext.ActionDescriptor.ActionName;
            string controllerName = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName;
            Person user = Session["userInfo"] as Person;
            if (user == null || !Helper.CheckAutorization(actionName, controllerName, user.RoleId))
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Home"},
                        {"action", "NoAccess"}
                    });
                return;
            }
        }

        // GET: Commandes
        public ActionResult Index()
        {
            var commandes = db.Commandes.Include(c => c.Copropriete).Include(c => c.Syndic);
            return View(commandes.ToList());
        }

        // GET: Commandes/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commande commande = db.Commandes.Find(id);
            if (commande == null)
            {
                return HttpNotFound();
            }
            return View(commande);
        }

        // GET: Commandes/Create
        public ActionResult Create()
        {
            Person user = Session["userInfo"] as Person;
            ViewBag.CoproprieteId = 
                new SelectList(db.Coproprietes.Where(_ => _.SyndicId == user.Id || _.SyndicAdjointId == user.Id), "Id", "Nom");
            return View();
        }

        // POST: Commandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Montant,Description,CoproprieteId")] Commande commande)
        {
            Person user = Session["userInfo"] as Person;

            if (ModelState.IsValid)
            {
                commande.DateCommande = DateTime.Now;
                commande.SyndicId = user.Id;
                db.Commandes.Add(commande);
                db.SaveChanges();
                var copropriete = db.Coproprietes.SingleOrDefault(_ => _.Id == commande.CoproprieteId);
                if(copropriete != null)
                {
                    copropriete.Tresorerie -= commande.Montant;
                    db.Entry(copropriete).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            ViewBag.CoproprieteId =
                new SelectList(db.Coproprietes.Where(_ => _.SyndicId == user.Id || _.SyndicAdjointId == user.Id), "Id", "Nom");
            ViewBag.SyndicId = user.Id;
            return View(commande);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Syndicata/Controllers/PaymantsController.cs
using Syndicata.Data;
using Syndicata.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Routing;

namespace Syndicata.Controllers
{
    public class PaymantsController : Controller
    {
        private SyndicataContext db = new SyndicataContext();

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            string actionName = filterContext.ActionDescriptor.ActionName;
            string controllerName = filterContext.ActionDescriptor.ControllerDescriptor.ControllerName;
            Person user = Session["userInfo"] as Person;
            if (user == null || !Helper.CheckAutorization(actionName, controllerName, user.RoleId))
            {
                filterContext.Result = new RedirectToRouteResult(
                    new RouteValueDictionary
                    {
                        {"controller", "Home"},
                        {"action", "NoAccess"}
                    });
                return;
            }
        }

        // GET: Paymants
        public ActionResult Index()
        {
            IQueryable<Paymant> paymants;
            Person user = Session["userInfo"] as Person;
            if(user.RoleId == Role.Copropritaire)
            {
                paymants = db.Paymants
                .Include(p => p.Payant)
                .Include(c => c.Copropriete)
                .Where(_ => _.PayantId == user.Id) ;
            }
            else
            {
                paymants = db.Paymants
                .Include(p => p.Payant)
                .Include(c => c.Copropriete);
            }
             
            return View(paymants.ToList());
        }

        // GET: Paymants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paymant paymant = db.Paymants
                .Include(_ => _.Payant)
                .Include(c => c.Copropriete)
                .SingleOrDefault(_ => _.Id == id);
            if (paymant == null)
            {
                return HttpNotFound();
            }
            return View(paymant);
        }

        // GET: Paymants/Create
        public ActionResult Create()
        {
            Person user = Session["userInfo"] as Person;

            ViewBag.PayantId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName");
            ViewBag.CoproprieteId = new SelectList(db.Coproprietes.Where(_ => _.SyndicId == user.Id || _.SyndicAdjointId == user.Id), "Id", "Nom");
            return View();
        }

        // POST: Paymants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Montant,Libelle,DatePaymant,PayantId,CoproprieteId")] Paymant paymant)
        {
            if (ModelState.IsValid)
            {
                db.Paymants.Add(paymant);
                db.SaveChanges();
                Copropriete copropriete = db.Coproprietes.SingleOrDefault(_ => _.Id == paymant.CoproprieteId);
                if (copropriete != null)
                {
                    copropriete.Tresorerie += paymant.Montant;
                    db.Entry(copropriete).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            Person user = Session["userInfo"] as Person;
            ViewBag.PayantId = new SelectList(db.People.Where(_ => _.RoleId == Role.Copropritaire), "Id", "FullName", paymant.PayantId);
            ViewBag.CoproprieteId = new SelectList(db.Coproprietes.Where(_ => _.SyndicId == user.Id || _.SyndicAdjointId == user.Id), "Id", "Nom");
            return View(paymant);
        }
    
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Syndicata/Controllers/PersonController.cs
using Syndicata.Data;
using Syndicata.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Routing;

namespace Syndicata.Controllers
{
    public class PersonController : Controller
    {
        private SyndicataContext db = new SyndicataContext();

       

        // GET: Person
        public ActionResult Index()
        {
            return View(db.People.ToList());
        }

        // GET: Person/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: Person/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Person/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Civilite,Nom,Prenom,DateNaissance,Telephone,Email,Password,RoleId")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: Person/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: Person/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Civilite,Nom,Prenom,DateNaissance,Telephone,Email,Password")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: Person/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: Person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Syndicata/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/style-starter.css" rel="stylesheet" />
    <a href="~/fonts/fontawesome-webfont.eot"></a>
    <a href="~/fonts/fontawesome-webfont.woff2"></a>
    <a href="~/fonts/fontawesome-webfont.woff"></a>
    <a href="~/fonts/fontawesome-webfont.ttf"></a>
    <a href="~/fonts/FontAwesome.otf"></a>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header class="w3l-header-nav">
        <!--/nav-->
        <nav class="navbar navbar-expand-lg navbar-light fill px-lg-0 py-0 px-3">
            <div class="container">
                <a class="navbar-brand" href="/">SYNDI <span>CATA</span></a>
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa icon-expand fa-bars"></span>
                    <span class="fa icon-close fa-times"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li>@Html.ActionLink("Acceuil", "Index", "Home", null, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("A Propos", "About", "Home", null, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Loi", "Loi", "Home", null, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })</li>
                        @if (Session["userInfo"] == null)
                        {
                            <li>@Html.ActionLink("Login", "Login", "Account", null, new { @class = "nav-link" })</li>
                        }
                        else
                        {
                            var user = Session["userInfo"] as Syndicata.Models.Person;
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Welcome @user.Nom @user.Prenom
                                </a>
                                <div class="hide" id="dropdownMenu" aria-labelledby="navbarDropdownMenuLink">
                                    @Html.ActionLink("Mon profile", "Profil", "Account", null, new { @class = "nav-link" })
                                    @if (user.RoleId == Syndicata.Models.Role.Copropritaire)
                                    {
                                        @Html.ActionLink("Consulter la liste des coproprietes", "Index", "Coproprietes", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Consulter les assembles general a venir", "Index", "AssembleGenerals", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Consulter les actions contre moi", "Index", "ActionCoproprietes", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Consulter mon historique de paymants", "Index", "Paymants", null, new { @class = "nav-link" })
                                    }
                                    else if (user.RoleId == Syndicata.Models.Role.Syndic || user.RoleId == Syndicata.Models.Role.SyndicAdjoint)
                                    {
                                        @Html.ActionLink("Gestion des syndics/habitants", "Index", "Person", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Gestion des coproprietes", "Index", "Coproprietes", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Gestion des appartements", "Index", "Appartements", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Gestion des assembles general", "Index", "AssembleGenerals", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Gestion des actions", "Index", "ActionCoproprietes", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Gestion des paymants", "Index", "Paymants", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Gestion des commandes", "Index", "Commandes", null, new { @class = "nav-link" })
                                        @Html.ActionLink("Logout", "Logout", "Account", null, new { @class = "nav-link" })
                                    }
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        <!--//nav-->
    </header>
    <div>
        @RenderBody()
    </div>
    <section class="w3l-footer-29-main">
        <div class="footer-29 py-5">
            <div class="container py-lg-4">
                <div class="row footer-top-29">
                    <div class="col-lg-3 col-md-6 col-sm-8 footer-list-29 footer-1 mt-lg-0 mt-5">
                        <h6 class="footer-title-29">Contactez Nous</h6>
                        <ul>
                            <li>
                                <p><span class="fa fa-map-marker"></span> Massira, Marrakech</p>
                            </li>
                            <li><a href="tel:05 24 10 20 52 "><span class="fa fa-phone"></span> 05 24 10 20 52 </a></li>
                            <li>
                                <a href="contact.syndicata@gmail.com" class="mail">
                                    <span class="fa fa-envelope-open-o"></span>
                                    contact.syndicata@gmail.com
                                </a>
                            </li>
                            <div class="main-social-footer-29 mt-4">
                                <a href="#facebook" class="facebook"><span class="fa fa-facebook"></span></a>
                                <a href="#twitter" class="twitter"><span class="fa fa-twitter"></span></a>
                                <a href="#instagram" class="instagram"><span class="fa fa-instagram"></span></a>
                                <a href="#linkedin" class="linkedin"><span class="fa fa-linkedin"></span></a>
                            </div>
                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-4 footer-list-29 footer-2 mt-lg-0 mt-5">

                        <ul>
                            <h6 class="footer-title-29">Contact</h6>
                            <li><a href="index.html">Accueil</a></li>
                            <li><a href="about.html">A Propos</a></li>
                            <li><a href="#blog"> Blog </a></li>
                            <li><a href="contact.html">Contact nous</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="w3l-footer-29-main w3l-copyright">
        <div class="container">
            <div class="bottom-copies">
                <p class="copy-footer-29 text-center">© 2021 SYNDICATA.</p>
            </div>
        </div>

        <!-- move top -->
        <button onclick="topFunction()" id="movetop" title="Go to top">
            &#10548;
        </button>
    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () {
            scrollFunction()
        };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                document.getElementById("movetop").style.display = "block";
            } else {
                document.getElementById("movetop").style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }

        $("#navbarDropdownMenuLink").click(function () {
            $("#dropdownMenu").toggleClass("hide");
        });



        $("body").ready(function () {
            $(document).click(function () {
                if (!$("#dropdownMenu").hasClass("hide")) {
                    $("#dropdownMenu").removeClass("hide");
                }
            });
        });
    </script>
    <!-- /move top -->

</body>
</html>